<script lang="ts">import type { PageProps } from './$types'; let { data, form }: PageProps = $props(); const categoryLabel: Record<string,string> = { depozit:'Depozit', oprema:'Oprema', ciscenje:'Čišćenje', posebne_naknade:'Posebne naknade', ostalo:'Ostalo' };</script>
<svelte:head><title>Dodatne opcije — Admin — Petroni</title></svelte:head>

<div class="max-w-[1500px]">
  <header class="mb-8"><p class="text-xs font-bold uppercase tracking-[0.18em] text-[#9a7600]">Najam</p><h1 class="mt-2 text-3xl font-black tracking-tight text-[#2b2b2b]">Dodatne opcije</h1><p class="mt-2 max-w-3xl text-sm leading-6 text-[#7a7f86]">Oprema, čišćenje, depoziti i posebne naknade koje ulaze u obračun rezervacije.</p></header>
  {#if form?.message}<div class="mb-6 rounded-xl border border-[#eadfba] bg-[#fffaf0] p-4 text-sm text-[#6f5600]">{form.message}</div>{/if}

  <section aria-labelledby="extras-heading"><div class="mb-4 flex items-center justify-between"><h2 id="extras-heading" class="text-lg font-bold text-[#2b2b2b]">Aktivne konfiguracijske stavke</h2><span class="text-xs text-[#8b9099]">{data.extras.length} opcija</span></div>
    <div class="grid gap-5 xl:grid-cols-2">
      {#each data.extras as extra}
        <form method="POST" action="?/saveExtra" class="rounded-2xl border border-[#e2e3e6] bg-white p-5">
          <input type="hidden" name="id" value={extra.id} /><input type="hidden" name="sort_order" value={extra.sort_order} /><input type="hidden" name="name_en" value={extra.name_en ?? ''} />
          <div class="mb-5 flex items-start justify-between gap-4"><div><p class="text-[11px] font-bold uppercase tracking-[.14em] text-[#9a7600]">{categoryLabel[extra.category ?? 'ostalo'] ?? 'Ostalo'}</p><p class="mt-1 font-semibold text-[#2b2b2b]">{extra.name_hr}</p></div><span class="rounded-md bg-[#fff7d6] px-3 py-1.5 text-sm font-bold tabular-nums text-[#806300]">{Number(extra.price).toFixed(2)} €</span></div>
          <div class="grid gap-4 sm:grid-cols-2">
            <label><span class="field-label">Naziv</span><input name="name_hr" class="field" value={extra.name_hr} required /></label><label><span class="field-label">Cijena</span><input name="price" type="number" step="0.01" class="field" value={extra.price} /></label>
            <label class="sm:col-span-2"><span class="field-label">Opis za gosta</span><textarea name="description_hr" rows="2" class="field resize-y">{extra.description_hr ?? ''}</textarea></label>
            <label><span class="field-label">Tip cijene</span><select name="price_type" class="field" value={extra.price_type}><option value="per_rental">Po najmu</option><option value="per_day">Po danu</option><option value="refundable">Povratno</option></select></label>
            <label><span class="field-label">Kategorija</span><select name="category" class="field" value={extra.category ?? ''}><option value="">Bez kategorije</option><option value="depozit">Depozit</option><option value="oprema">Oprema</option><option value="ciscenje">Čišćenje</option><option value="posebne_naknade">Posebne naknade</option><option value="ostalo">Ostalo</option></select></label>
            <label><span class="field-label">Automatska primjena</span><select name="auto_apply_rule" class="field" value={extra.auto_apply_rule ?? ''}><option value="">Ručno odabire gost</option><option value="border_crossing">Prelazak granice</option><option value="festival">Festival</option></select></label>
            <label><span class="field-label">Najveća količina</span><input name="max_qty" type="number" min="1" class="field" value={extra.max_qty} /></label>
          </div>
          <div class="mt-5 flex flex-wrap items-center justify-between gap-4 border-t border-[#ededf0] pt-4"><label class="flex items-center gap-2 text-sm font-semibold text-[#454a50]"><input type="checkbox" name="is_required" checked={extra.is_required} class="h-4 w-4 accent-[#F5C518]" /> Obavezna stavka</label><div class="flex items-center gap-4"><button type="submit" formaction="?/deleteExtra" onclick={(event) => { if (!confirm('Obrisati dodatnu opciju?')) event.preventDefault(); }} class="text-sm font-semibold text-red-600 hover:underline">Obriši</button><button class="btn btn-primary px-5 py-2.5 text-black">Spremi opciju</button></div></div>
        </form>
      {/each}
    </div>
  </section>

  <section class="mt-12 rounded-2xl border border-dashed border-[#d6c77f] bg-[#fffdf5] p-6"><div class="mb-5"><p class="text-[11px] font-bold uppercase tracking-[.15em] text-[#9a7600]">Nova opcija</p><h2 class="mt-1 text-lg font-bold text-[#2b2b2b]">Dodajte novu stavku obračuna</h2></div>
    <form method="POST" action="?/saveExtra"><div class="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><label><span class="field-label">Naziv HR</span><input name="name_hr" class="field" required /></label><label><span class="field-label">Naziv EN</span><input name="name_en" class="field" /></label><label><span class="field-label">Cijena</span><input name="price" type="number" step="0.01" value="0" class="field" /></label><label><span class="field-label">Tip cijene</span><select name="price_type" class="field"><option value="per_rental">Po najmu</option><option value="per_day">Po danu</option><option value="refundable">Povratno</option></select></label><label><span class="field-label">Kategorija</span><select name="category" class="field"><option value="oprema">Oprema</option><option value="depozit">Depozit</option><option value="ciscenje">Čišćenje</option><option value="posebne_naknade">Posebne naknade</option><option value="ostalo">Ostalo</option></select></label><label><span class="field-label">Automatska primjena</span><select name="auto_apply_rule" class="field"><option value="">Ručno odabire gost</option><option value="border_crossing">Prelazak granice</option><option value="festival">Festival</option></select></label><label><span class="field-label">Max količina</span><input name="max_qty" type="number" min="1" value="1" class="field" /></label><label><span class="field-label">Redoslijed</span><input name="sort_order" type="number" value="0" class="field" /></label><label class="md:col-span-2 xl:col-span-4"><span class="field-label">Opis HR</span><textarea name="description_hr" rows="3" class="field"></textarea></label></div><div class="mt-5 flex flex-wrap items-center justify-between gap-4"><label class="flex items-center gap-2 text-sm font-semibold text-[#454a50]"><input name="is_required" type="checkbox" class="h-4 w-4 accent-[#F5C518]" /> Obavezna stavka</label><button class="btn btn-dark px-6 py-3">Dodaj opciju</button></div></form>
  </section>
</div>
